### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by rowhitswami** [rowhitswami/hacktoberfest18-ft#2]
Improve the instruction so that <b>First Timer Contributor</b> can understand it properly and check for grammatical mistakes.

**Comment by Hackhard** [comment]
@rowhitswami I am taking this!

**Comment by rowhitswami** [comment]
@Hackhard Are you on it?

**Comment by fineanmol** [comment]
Live page of Contributors. [Contributors](https://fineanmol.github.io/Hacktoberfest2k18/Contributors.html)
Don't forget to spread love and if you like to give us a ⭐️
